ALTER TABLE products ADD COLUMN weight REAL DEFAULT 0;
ALTER TABLE products ADD COLUMN width REAL DEFAULT 0;
ALTER TABLE products ADD COLUMN height REAL DEFAULT 0;
ALTER TABLE products ADD COLUMN length REAL DEFAULT 0;
